include "/etc/bind/rndc.key";

options {
    directory "/var/cache/bind";
    recursion yes;
    allow-recursion { any; };
    listen-on { any; };
    allow-query { any; };
    dnssec-validation no;
};

controls {
    inet 0.0.0.0 port 953 allow { any; } keys { "rndc-key"; };
};

zone "corp.local" {
    type master;
    file "/etc/bind/zones/corp.local.zone";
    allow-transfer { any; };
};
