[global]
   workgroup = CORP
   server string = NAS Storage Server
   server signing = disabled
   map to guest = Bad User

[data]
   path = /srv/nas
   browsable = yes
   writable = yes
   guest ok = yes
   read only = no
